server {
  listen       80;

  root   /usr/share/nginx/html/ssr;

  location / {
    index index.html;
    try_files $uri $uri/ /index.html;
    expires -1;
  }
  error_page 500 502 503 504 /50x.html;
  location /50.html {
      root /usr/share/nginx/html/ssr;
    }
}
